name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet '8.x'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

      # - name: Install dependencies
      #   run: dotnet add package Iot.Device.Bindings --version 3.1.0 --project HardwareMonitor/HardwareMonitor.csproj

      # - name: Install dependencies
      #   run: dotnet restore

      - name: Install dependencies
        run: dotnet restore WinFormsApp1/WinFormsApp1.csproj

      - name: Build
        run: dotnet build WinFormsApp1/WinFormsApp1.csproj

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            WinFormsApp1/bin/Debug/net8.0-windows/WinFormsApp1.exe
          tag_name: ${{ github.run_id }}
          release_name: ${{ github.run_id }}
          body: |
            Changes in this Release
            - First release

      # - name: Build
      #   run: dotnet run --project WinFormsApp1/WinFormsApp1.csproj

      # - name: Test with the dotnet CLI
      #   run: dotnet test

      # - name: Upload dotnet test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dotnet-results-8.x
      #     path: TestResults-8.x
      #   # Use always() to always run this step to publish test results when there are test failures
      #   if: ${{ always() }}
