name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet '8.x'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Display dotnet version
        run: dotnet --version

      - name: Install dependencies
        run: |
          dotnet restore WindowsFormsApp1\WindowsFormsApp1.csproj
          nuget restore WindowsFormsApp1\WindowsFormsApp1.csproj

      - name: Clean
        run: dotnet clean WindowsFormsApp1\WindowsFormsApp1.csproj -c Release

      - name: Build
        run: dotnet build WindowsFormsApp1\WindowsFormsApp1.csproj -c Release

      # - name: Copy build artifact
      #   run: cp WindowsFormsApp1\bin\Release\net8.0-windows\win-x64\publish\WindowsFormsApp1.exe ${{ runner.temp }}\WindowsFormsApp1.exe

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: TempManager
      #     path: ${{ runner.temp }}\WindowsFormsApp1.exe
